// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTemperatureChange();
void onAlarmTriggeredChange();

float temperature;
bool alarmTriggered;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(alarmTriggered, READWRITE, ON_CHANGE, onAlarmTriggeredChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
